[package]
name = "diesel-2-0-1-regression"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4" }
diesel = { version = "=2.0.0", features = ["postgres", "chrono"] }
#diesel = { version = "=2.0.1", features = ["postgres", "chrono"] }
dotenvy = "0.15"
